<?php

namespace App\Model;

class Roles
{
    const ROLES_TODOS_USUARIOS=[
        'ADMIN'=>'ROLE_ADMIN',
        'ADMINISTRADOR BARRIO'=>'ROLE_ADMIN_BARRIO',
        'PROPIETARIO'=>'ROLE_PROPIETARIO',
        'PROFESIONAL'=>'ROLE_PROFESIONAL',
    ];
    const ROLES_USUARIOS_SISTEMA=[
        'ADMINISTRADOR BARRIO'=>'ROLE_ADMIN_BARRIO',
        'PROPIETARIO'=>'ROLE_PROPIETARIO',
        'PROFESIONAL'=>'ROLE_PROFESIONAL',
    ];

    const ROLE_ADMIN = 'ROLE_ADMIN';
    const ROLE_ADMIN_BARRIO = 'ROLE_ADMIN_BARRIO';
    const ROLE_PROFESIONAL = 'ROLE_PROFESIONAL';
    const ROLE_PROPIETARIO = 'ROLE_PROPIETARIO';


}