<?php

namespace App\Form;

use App\Entity\Vtmclh;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VtmclhFilterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('vtmclhRubr01',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhRubr03',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhRubr04',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhRubr05',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhRubr06',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhRubr07',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhRubr08',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhRubr09',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhRubr10',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhRubr02',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNombre',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNrosub',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhRespon',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDirecc',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNumero',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDppiso',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDeptos',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCodfil',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCodpai',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCodpos',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhMunicp',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhFletes',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTelefn',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNrofax',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNtelex',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCndiva',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTipdoc',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNrodoc',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhVnddor',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCobrad',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhJurisd',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCodzon',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhActivd',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCatego',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCndpag',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCndpre',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCodcrd',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhGrubon',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCamion',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCamalt',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTracod',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDirep1',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDirep2',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDirep3',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDirep4',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDirep5',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhHorrec',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDirent',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhPaient',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCodent',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhJurent',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhZonent',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCopivt',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCopifc',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCopist',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTextos',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTipdo1',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNrodo1',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTipdo2',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNrodo2',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTipdo3',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNrodo3',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTipdo4',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNrodo4',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTipdo5',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNrodo5',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDireml',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhSegpro',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhContad',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhEdisub',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCuenta',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhMaxitm',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDifdia',null,[
                        'required'=>false
                    ]
                )
//            ->add('vtmclhDifdes',null,[
//                        'required'=>false
//                    ]
//                )
//            ->add('vtmclhDifhas',null,[
//                        'required'=>false
//                    ]
//                )
            ->add('vtmclhPerina',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhImpdif',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhEmail',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCndint',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDistri',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDeposi',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhSector',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNrodis',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhOleole',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhBmpbmp',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhInhibe',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhPrmxpr',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhPrmipr',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTrafcr',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCodcof',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhModcpt',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTipcpt',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCodcpt',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhLiscli',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTipopr',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCodopr',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhModpag',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhTippag',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhMedpag',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhLanexp',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhGenxml',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhGlndes',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCodexp',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhOblcon',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDeptra',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhSectra',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhFisjur',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhApell1',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhApell2',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNomb01',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhNomb02',null,[
                        'required'=>false
                    ]
                )
            ->add('usrVtmclhLocpro',null,[
                        'required'=>false
                    ]
                )
            ->add('usrVtmclhCodare',null,[
                        'required'=>false
                    ]
                )
            ->add('usrVtmclhTienda',null,[
                        'required'=>false
                    ]
                )
            ->add('usrVtmclhDepo',null,[
                        'required'=>false
                    ]
                )
            ->add('usrVtmclhGrptan',null,[
                        'required'=>false
                    ]
                )
            ->add('usrVtmclhRefcli',null,[
                        'required'=>false
                    ]
                )
            ->add('usrVtmclhCodemp',null,[
                        'required'=>false
                    ]
                )
            ->add('usrVtmclhRefloc',null,[
                        'required'=>false
                    ]
                )
            ->add('usrVtmclhEstcom',null,[
                        'required'=>false
                    ]
                )
//            ->add('vtmclhFecalt',null,[
//                        'required'=>false
//                    ]
//                )
//            ->add('vtmclhFecmod',null,[
//                        'required'=>false
//                    ]
//                )
            ->add('vtmclhUserid',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhUltopr',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhDebaja',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhHormov',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhModule',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhOalias',null,[
                        'required'=>false
                    ]
                )
//            ->add('vtmclhTstamp',null,[
//                        'required'=>false
//                    ]
//                )
            ->add('vtmclhLottra',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhLotrec',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhLotori',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhSysver',null,[
                        'required'=>false
                    ]
                )
            ->add('vtmclhCmpver',null,[
                        'required'=>false
                    ]
                )
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
        ]);
    }
}
